/*1*/
INSERT INTO CATEGORIA 
VALUES ((SELECT MAX(ID_CATEGORIA+10) FROM CATEGORIA), 'MUSICAL', (SELECT MIN(PRECIO*1.2) FROM CATEGORIA), (SELECT SUM(DIAS_PRESTAMO) FROM CATEGORIA WHERE NOM_CATEGORIA IN ('NORMAL', 'CINE ARTE')));
       

INSERT INTO DIRECTOR
VALUES ((SELECT MAX(ID_DIRECTOR+1) FROM DIRECTOR), 'HOOPER');


INSERT INTO TITULO 
VALUES ((SELECT MAX(COD_TITULO+1) FROM TITULO), 'Los Miserables', (SELECT MAX(ID_DIRECTOR) FROM DIRECTOR), (SELECT (ID_PAIS) FROM PAIS WHERE NOM_PAIS = 'INGLATERRA'), (SELECT (ID_CATEGORIA) FROM CATEGORIA WHERE NOM_CATEGORIA = 'MUSICAL'), '5', '2012', 'Un ex convicto, alcalde y fugitivo');


INSERT INTO COPIA 
VALUES ((SELECT MAX(COD_COPIA+1) FROM COPIA), (SELECT (COD_TITULO) FROM TITULO WHERE NOM_TITULO = 'Los Miserables'), 'D');


/*2*/
UPDATE prestamo A set A.FECHA_TERMINO = SYSDATE+5, A.FECHA_DEVOLUCION = NULL, A.ESTADO = 'P'
WHERE (A.fecha_termino - A.fecha_inicio) > 3
AND A.COD_COPIA =(SELECT B.COD_COPIA FROM COPIA B WHERE A.COD_COPIA = B.COD_COPIA 
                  AND B.COD_TITULO =(SELECT C.COD_TITULO FROM TITULO C WHERE B.COD_TITULO = C.COD_TITULO 
                                                                    AND C.DESCRIPCION LIKE('%AMOR%'))); 

/*3*/
